// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tygiwyufpleokiwqkbyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5Z2l3eXVmcGxlb2tpd3FrYnlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NTAyMjgsImV4cCI6MjA2MDUyNjIyOH0.HZvEWnL3rgYcnBqUni3QTsjYZ74jDMq28A0BFqTIhUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);